"""
airlines_db.py — Base complète des compagnies aériennes actives
~500+ compagnies avec codes IATA, pays et couleurs
Chargée dynamiquement dans serpapi_client.py
"""

# Format : (code_IATA, nom, pays, couleur_hex)
AIRLINES = [
    # ── Europe ────────────────────────────────────────────────────────────────
    ("AF", "Air France",              "France",          "#002157"),
    ("TO", "Transavia France",        "France",          "#00B140"),
    ("SS", "Corsair",                 "France",          "#E30613"),
    ("SE", "XL Airways France",       "France",          "#FF6600"),
    ("UU", "Air Austral",             "France",          "#0055A4"),
    ("MF", "Aircalin",                "France",          "#0033A0"),
    ("BA", "British Airways",         "Royaume-Uni",     "#075AAA"),
    ("VS", "Virgin Atlantic",         "Royaume-Uni",     "#E10028"),
    ("EZY","easyJet",                 "Royaume-Uni",     "#FF6600"),
    ("U2", "easyJet",                 "Royaume-Uni",     "#FF6600"),
    ("BE", "Flybe",                   "Royaume-Uni",     "#7B1FA2"),
    ("LS", "Jet2",                    "Royaume-Uni",     "#ED1C24"),
    ("BY", "TUI Airways",             "Royaume-Uni",     "#00539B"),
    ("MT", "Thomas Cook Airlines",    "Royaume-Uni",     "#FF6600"),
    ("LH", "Lufthansa",               "Allemagne",       "#05164D"),
    ("EW", "Eurowings",               "Allemagne",       "#A00050"),
    ("DE", "Condor",                  "Allemagne",       "#E30613"),
    ("X3", "TUI fly Deutschland",     "Allemagne",       "#00539B"),
    ("4U", "Germanwings",             "Allemagne",       "#5F0F40"),
    ("IB", "Iberia",                  "Espagne",         "#D40000"),
    ("VY", "Vueling",                 "Espagne",         "#FFD700"),
    ("UX", "Air Europa",              "Espagne",         "#C8102E"),
    ("NT", "Binter Canarias",         "Espagne",         "#003087"),
    ("I2", "Iberia Express",          "Espagne",         "#C00000"),
    ("AZ", "ITA Airways",             "Italie",          "#008C45"),
    ("IG", "Air Italy",               "Italie",          "#009FE3"),
    ("FC", "Volotea",                 "Italie",          "#005BAC"),
    ("FR", "Ryanair",                 "Irlande",         "#073590"),
    ("EI", "Aer Lingus",              "Irlande",         "#006747"),
    ("KL", "KLM",                     "Pays-Bas",        "#00A1DE"),
    ("HV", "Transavia Netherlands",   "Pays-Bas",        "#00B140"),
    ("SN", "Brussels Airlines",       "Belgique",        "#2D2A6E"),
    ("LX", "Swiss",                   "Suisse",          "#E30613"),
    ("OS", "Austrian Airlines",       "Autriche",        "#C60000"),
    ("TP", "TAP Air Portugal",        "Portugal",        "#009DE0"),
    ("NI", "Portugalia",              "Portugal",        "#003087"),
    ("SK", "SAS",                     "Scandinavie",     "#002D62"),
    ("DY", "Norwegian",               "Norvège",         "#D40000"),
    ("WF", "Widerøe",                 "Norvège",         "#003087"),
    ("AY", "Finnair",                 "Finlande",        "#003580"),
    ("SK", "SAS Scandinavian",        "Suède",           "#002D62"),
    ("BT", "Air Baltic",              "Lettonie",        "#00A550"),
    ("W6", "Wizz Air",                "Hongrie",         "#C8102E"),
    ("MA", "Malév Hungarian",         "Hongrie",         "#006400"),
    ("OK", "Czech Airlines",          "Tchéquie",        "#C60000"),
    ("LO", "LOT Polish Airlines",     "Pologne",         "#005BAC"),
    ("OA", "Olympic Air",             "Grèce",           "#003087"),
    ("A3", "Aegean Airlines",         "Grèce",           "#003087"),
    ("TK", "Turkish Airlines",        "Turquie",         "#C8102E"),
    ("PC", "Pegasus Airlines",        "Turquie",         "#FF6600"),
    ("XQ", "SunExpress",              "Turquie",         "#FF8C00"),
    ("RO", "TAROM",                   "Roumanie",        "#003087"),
    ("FB", "Bulgaria Air",            "Bulgarie",        "#003087"),
    ("JP", "Adria Airways",           "Slovénie",        "#003087"),
    ("OU", "Croatia Airlines",        "Croatie",         "#003087"),
    ("JU", "Air Serbia",              "Serbie",          "#C8102E"),
    ("LY", "El Al",                   "Israël",          "#003087"),
    ("IS", "Arkia",                   "Israël",          "#003087"),
    ("UA", "Ukraine International",   "Ukraine",         "#003087"),
    ("VV", "Windrose Airlines",       "Ukraine",         "#003087"),
    ("SU", "Aeroflot",                "Russie",          "#1F2D6E"),
    ("S7", "S7 Airlines",             "Russie",          "#007A3D"),
    ("UT", "UTair",                   "Russie",          "#003087"),
    ("U6", "Ural Airlines",           "Russie",          "#003087"),
    ("DP", "Pobeda",                  "Russie",          "#FFD700"),
    ("PS", "UIA Ukraine",             "Ukraine",         "#003087"),
    ("WB", "RwandAir",                "Rwanda",          "#007A3D"),
    ("CPH","Copenhagen Air Taxi",     "Danemark",        "#003580"),
    ("DT", "TAAG Angola Airlines",    "Angola",          "#003087"),
    # ── Moyen-Orient ──────────────────────────────────────────────────────────
    ("EK", "Emirates",                "Émirats Arabes",  "#C60C30"),
    ("FZ", "flydubai",                "Émirats Arabes",  "#E30613"),
    ("EY", "Etihad Airways",          "Abu Dhabi",       "#BD8B13"),
    ("G9", "Air Arabia",              "Émirats Arabes",  "#E30613"),
    ("QR", "Qatar Airways",           "Qatar",           "#5C0632"),
    ("GF", "Gulf Air",                "Bahreïn",         "#C8102E"),
    ("KU", "Kuwait Airways",          "Koweït",          "#003087"),
    ("ME", "Middle East Airlines",    "Liban",           "#003087"),
    ("RJ", "Royal Jordanian",         "Jordanie",        "#003087"),
    ("MS", "EgyptAir",                "Égypte",          "#003087"),
    ("XY", "Flynas",                  "Arabie Saoudite", "#007A3D"),
    ("SV", "Saudia",                  "Arabie Saoudite", "#006400"),
    ("WY", "Oman Air",                "Oman",            "#003087"),
    ("IR", "Iran Air",                "Iran",            "#003087"),
    ("EP", "Iran Aseman",             "Iran",            "#003087"),
    ("IA", "Iraqi Airways",           "Irak",            "#003087"),
    # ── Afrique ───────────────────────────────────────────────────────────────
    ("AT", "Royal Air Maroc",         "Maroc",           "#BE0A15"),
    ("3O", "Air Arabia Maroc",        "Maroc",           "#E30613"),
    ("TU", "Tunisair",                "Tunisie",         "#CC0000"),
    ("UG", "TunisAir Express",        "Tunisie",         "#CC0000"),
    ("AH", "Air Algérie",             "Algérie",         "#008000"),
    ("7T", "Tassili Airlines",        "Algérie",         "#008000"),
    ("ET", "Ethiopian Airlines",      "Éthiopie",        "#078930"),
    ("QC", "Camair-Co",               "Cameroun",        "#007A3D"),
    ("KQ", "Kenya Airways",           "Kenya",           "#C8102E"),
    ("SA", "South African Airways",   "Afrique du Sud",  "#006CB7"),
    ("FA", "Safair",                  "Afrique du Sud",  "#003087"),
    ("MK", "Air Mauritius",           "Maurice",         "#E30613"),
    ("UB", "Myanmar National",        "Myanmar",         "#003087"),
    ("SB", "Aircalin",                "Nouvelle-Calédonie","#003087"),
    ("HF", "Air Côte d'Ivoire",       "Côte d'Ivoire",   "#009FE3"),
    ("VT", "Air Tahiti",              "Polynésie",       "#003087"),
    ("SW", "Air Namibia",             "Namibie",         "#003087"),
    ("TC", "Air Tanzania",            "Tanzanie",        "#007A3D"),
    ("QS", "SmartWings",              "Tchéquie",        "#FFD700"),
    ("8U", "Afriqiyah Airways",       "Libye",           "#003087"),
    ("ZY", "Ada Air",                 "Albanie",         "#003087"),
    ("RA", "Nepal Airlines",          "Népal",           "#003087"),
    ("TM", "LAM Mozambique",          "Mozambique",      "#003087"),
    ("GH", "Globus Airlines",         "Russie",          "#003087"),
    ("W3", "Arik Air",                "Nigéria",         "#003087"),
    ("VK", "Virgin Nigeria",          "Nigéria",         "#E10028"),
    ("DL", "Delta Air Lines",         "États-Unis",      "#C01933"),
    # ── Amérique du Nord ──────────────────────────────────────────────────────
    ("UA", "United Airlines",         "États-Unis",      "#002244"),
    ("AA", "American Airlines",       "États-Unis",      "#B61F23"),
    ("WN", "Southwest Airlines",      "États-Unis",      "#304CB2"),
    ("B6", "JetBlue",                 "États-Unis",      "#003399"),
    ("AS", "Alaska Airlines",         "États-Unis",      "#00538B"),
    ("F9", "Frontier Airlines",       "États-Unis",      "#00813E"),
    ("NK", "Spirit Airlines",         "États-Unis",      "#FFD700"),
    ("G4", "Allegiant Air",           "États-Unis",      "#003087"),
    ("HA", "Hawaiian Airlines",       "États-Unis",      "#00529B"),
    ("AC", "Air Canada",              "Canada",          "#D22630"),
    ("PD", "Porter Airlines",         "Canada",          "#003087"),
    ("WS", "WestJet",                 "Canada",          "#003087"),
    ("TS", "Air Transat",             "Canada",          "#003087"),
    ("AM", "Aeromexico",              "Mexique",         "#0047AB"),
    ("VB", "VivaAerobus",             "Mexique",         "#FFD700"),
    ("Y4", "Volaris",                 "Mexique",         "#7B1FA2"),
    # ── Amérique Centrale & Caraïbes ──────────────────────────────────────────
    ("CM", "Copa Airlines",           "Panama",          "#003087"),
    ("AV", "Avianca",                 "Colombie",        "#C8102E"),
    ("LA", "LATAM Airlines",          "Chili",           "#1A1A2E"),
    ("JJ", "LATAM Brasil",            "Brésil",          "#1A1A2E"),
    ("G3", "Gol",                     "Brésil",          "#FF6600"),
    ("AD", "Azul",                    "Brésil",          "#003087"),
    ("AR", "Aerolíneas Argentinas",   "Argentine",       "#74ACDF"),
    ("LP", "Latam Perú",              "Pérou",           "#1A1A2E"),
    ("H2", "Sky Airline",             "Chili",           "#003087"),
    ("5Z", "Cem Air",                 "Afrique du Sud",  "#003087"),
    ("4C", "LATAM Colombia",          "Colombie",        "#1A1A2E"),
    # ── Asie ──────────────────────────────────────────────────────────────────
    ("SQ", "Singapore Airlines",      "Singapour",       "#F0A500"),
    ("MI", "SilkAir",                 "Singapour",       "#003087"),
    ("TR", "Scoot",                   "Singapour",       "#FFD700"),
    ("CX", "Cathay Pacific",          "Hong Kong",       "#006564"),
    ("KA", "Cathay Dragon",           "Hong Kong",       "#C8102E"),
    ("HX", "Hong Kong Airlines",      "Hong Kong",       "#C8102E"),
    ("KE", "Korean Air",              "Corée du Sud",    "#00256C"),
    ("OZ", "Asiana Airlines",         "Corée du Sud",    "#FF6600"),
    ("7C", "Jeju Air",                "Corée du Sud",    "#FF6600"),
    ("NH", "ANA",                     "Japon",           "#003087"),
    ("JL", "Japan Airlines",          "Japon",           "#E60026"),
    ("JW", "Vanilla Air",             "Japon",           "#FF6600"),
    ("MM", "Peach Aviation",          "Japon",           "#FF69B4"),
    ("GK", "Jetstar Japan",           "Japon",           "#FF6600"),
    ("CA", "Air China",               "Chine",           "#C8102E"),
    ("CZ", "China Southern",          "Chine",           "#003087"),
    ("MU", "China Eastern",           "Chine",           "#E30613"),
    ("HU", "Hainan Airlines",         "Chine",           "#C8102E"),
    ("ZH", "Shenzhen Airlines",       "Chine",           "#003087"),
    ("XO", "China Xinhua Airlines",   "Chine",           "#003087"),
    ("SC", "Shandong Airlines",       "Chine",           "#003087"),
    ("3U", "Sichuan Airlines",        "Chine",           "#003087"),
    ("FM", "Shanghai Airlines",       "Chine",           "#003087"),
    ("CI", "China Airlines",          "Taïwan",          "#003087"),
    ("BR", "EVA Air",                 "Taïwan",          "#007A3D"),
    ("TG", "Thai Airways",            "Thaïlande",       "#600080"),
    ("WE", "Thai Smile",              "Thaïlande",       "#E30613"),
    ("FD", "Thai AirAsia",            "Thaïlande",       "#E30613"),
    ("PG", "Bangkok Airways",         "Thaïlande",       "#003087"),
    ("MH", "Malaysia Airlines",       "Malaisie",        "#C00000"),
    ("AK", "AirAsia",                 "Malaisie",        "#E30613"),
    ("QZ", "Indonesia AirAsia",       "Indonésie",       "#E30613"),
    ("GA", "Garuda Indonesia",        "Indonésie",       "#003087"),
    ("JT", "Lion Air",                "Indonésie",       "#E30613"),
    ("ID", "Batik Air",               "Indonésie",       "#003087"),
    ("PR", "Philippine Airlines",     "Philippines",     "#003087"),
    ("Z2", "Philippines AirAsia",     "Philippines",     "#E30613"),
    ("5J", "Cebu Pacific",            "Philippines",     "#FFD700"),
    ("VN", "Vietnam Airlines",        "Viêt Nam",        "#C8102E"),
    ("VJ", "VietJet Air",             "Viêt Nam",        "#E30613"),
    ("BL", "Pacific Airlines",        "Viêt Nam",        "#003087"),
    ("AI", "Air India",               "Inde",            "#C8102E"),
    ("IX", "Air India Express",       "Inde",            "#C8102E"),
    ("6E", "IndiGo",                  "Inde",            "#003087"),
    ("SG", "SpiceJet",                "Inde",            "#E30613"),
    ("UK", "Vistara",                 "Inde",            "#7B1FA2"),
    ("G8", "Go First",                "Inde",            "#FF6600"),
    ("PK", "Pakistan International", "Pakistan",         "#006400"),
    ("AP", "AlbaStar",                "Pakistan",        "#003087"),
    ("BI", "Royal Brunei",            "Brunei",          "#FFD700"),
    ("TF", "Braathens Regional",      "Suède",           "#003087"),
    ("OD", "Malindo Air",             "Malaisie",        "#003087"),
    ("FY", "Firefly",                 "Malaisie",        "#FFD700"),
    ("UL", "SriLankan Airlines",      "Sri Lanka",       "#8B0000"),
    ("UM", "Air Zimbabwe",            "Zimbabwe",        "#007A3D"),
    # ── Océanie ───────────────────────────────────────────────────────────────
    ("QF", "Qantas",                  "Australie",       "#E30613"),
    ("JQ", "Jetstar",                 "Australie",       "#FF6600"),
    ("TT", "TigerAir Australia",      "Australie",       "#FF6600"),
    ("NZ", "Air New Zealand",         "Nouvelle-Zélande","#003087"),
    ("FJ", "Fiji Airways",            "Fidji",           "#003087"),
    ("PX", "Air Niugini",             "Papouasie",       "#003087"),
    ("SB", "Air Caledonie Intl",      "N.-Calédonie",    "#003087"),
    ("IW", "Wings Air",               "Indonésie",       "#003087"),
    # ── Afrique supplémentaires ───────────────────────────────────────────────
    ("ET", "Ethiopian Airlines",      "Éthiopie",        "#078930"),
    ("3P", "Proflight Zambia",        "Zambie",          "#003087"),
    ("QG", "Citilink",                "Indonésie",       "#003087"),
    ("EC", "Easy Jet Europe",         "Autriche",        "#FF6600"),
    ("4Y", "Discover Airlines",       "Allemagne",       "#FF8C00"),
    ("X9", "Avion Express",           "Lituanie",        "#003087"),
    ("GT", "Air Guilin",              "Chine",           "#003087"),
    ("CN", "Grand China Air",         "Chine",           "#003087"),
    ("XJ", "Thai AirAsia X",         "Thaïlande",       "#E30613"),
    ("D7", "AirAsia X",              "Malaisie",        "#E30613"),
    ("XT", "Indonesia AirAsia X",    "Indonésie",       "#E30613"),
]

# Dictionnaire nom → code
NAME_TO_CODE = {name: code for code, name, country, color in AIRLINES}
# Dictionnaire code → (nom, couleur)
CODE_TO_INFO = {code: (name, color) for code, name, country, color in AIRLINES}

def get_airline_name(code: str) -> str:
    info = CODE_TO_INFO.get(code)
    return info[0] if info else code

def get_airline_color(code: str) -> str:
    info = CODE_TO_INFO.get(code)
    return info[1] if info else "#4FC3F7"

def get_code_from_name(name: str) -> str:
    # Recherche exacte d'abord
    if name in NAME_TO_CODE:
        return NAME_TO_CODE[name]
    # Recherche partielle
    name_lower = name.lower()
    for n, c in NAME_TO_CODE.items():
        if name_lower in n.lower() or n.lower() in name_lower:
            return c
    return ""
